name: Assign PR Author
on:
  pull_request:
    types: [opened]
jobs:
  assign-pr-author:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign PR creator
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: [context.payload.pull_request.user.login]
            })
